### ISSUE TITLE
[META] Network Model

### ISSUE THREAD

**Issue by jthrilly** [scriptnet-project/scriptnet#2]
- [ ] Create example of expected graph schema. Consider things like parallel edges, attribute types we will need to store. (https://github.com/wwqrd/scriptnet/issues/6)
- [ ] Research options for network/graph libraries that can represent this schema. Try to find the one Josh mentioned in chat.
- [ ] Integrate this library into the app
- [ ] Create simple interface for components to perform CRUD operations on network entities 
  - React now features `useReducer()`, which means we could work using a similar principle to redux without actually using an app wide redux state. Also https://redux-actions.js.org/ is kind of a cool thing we could use to model 'ducks' as we do in NC.
