### ISSUE TITLE
[META] Visualisation Component

### ISSUE THREAD

**Issue by jthrilly** [scriptnet-project/scriptnet#4]
- [ ] Finalize requirements: 
  - [ ] shapes? clicking node/edges?
  - [ ] interactivity - which types of interaction does the visualisation require?
  - [ ] layout computation - compute once? constant "physics" model?
  - [ ] performance
- [ ] Review available options in light of requirements and select library
- [ ] Implement visualisation view
  - [ ] Integrate library by creating visualisation component
  - [ ] Implement properties on the component to allow customisation / change behaviour. 
  - [ ] Integrate with network model
