### ISSUE TITLE
[META] UI Framework

### ISSUE THREAD

**Issue by wwqrd** [scriptnet-project/scriptnet#5]
We should use an existing UI framework to save time styling the app.

Examples:
- https://developer.microsoft.com/en-us/fluentui (strong preference for this one!)
- Material
- Bootstrap

Deliverable:
- [x] Install UI lib and get it working with any build tools we may be using
- [x] Update README to link to any relevant documentation
- [x] Update any existing components to use UI library (assuming this happens early on so that isn't much work)
